---
- name: Powershell Sleep
  hosts: all
  gather_facts: false
  ignore_errors: true

  tasks:
    - name: Sleep
      ansible.windows.win_powershell:
        script: |
          echo "Hello World"
          Start-Sleep -Seconds 120
      timeout: 10

    - name: Sleep
      ansible.windows.win_powershell:
        script: |
          echo "Hello World"
          Start-Sleep -Seconds 120
      timeout: 15

    - name: Sleep
      ansible.windows.win_powershell:
        script: |
          echo "Hello World"
          Start-Sleep -Seconds 120
